# -*- coding: utf-8 -*-
"""DataPreprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbCI0VCM8cVncUTxqC-9W5ceGwwRFiV9

Data Standardization
"""

import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#loading the dataset
dataset=sklearn.datasets.load_breast_cancer()
print(dataset)

#loading the data to a pandas dataframe
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

df.head()

df.shape

x=df
y=dataset.target

print(x)
print(y)

#Splitting data into training data and testing data before standardization
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

print(x.shape,x_train.shape,x_test.shape)

#standardize the data for common format std=1
print(dataset.data.std())

scaler=StandardScaler()

scaler.fit(x_train)

x_train_standardized=scaler.transform(x_train)
print(x_train_standardized)
#we can see values in similar range

x_train_standardized=scaler.transform(x_train)
print(x_train_standardized)
#we can see values in similar range

x_test_standardized=scaler.transform(x_test)
print(x_train_standardized.std())
print(x_test_standardized.std())